apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - crossplane.yml
    - provider-incus.yml
    - provider-incus-secret.yml
    - provider-incus-providerconfig.yml
    - provider-incus-runtimeconfig.yml
    - provider-incus-podmonitor.yml
