apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - crossplane.yml
    - provider-incus.yml
    - provider-openfga.yml
    - provider-openfga-secret.yml
    - provider-openfga-providerconfig.yml
    - provider-incus-secret.yml
    - provider-incus-providerconfig.yml
    - provider-incus-runtimeconfig.yml
    - provider-incus-podmonitor.yml
    - crossplane-podmonitor.yml
    - openfga-store.yml
