apiVersion: v1
kind: Secret
metadata:
    name: provider-openfga-creds
    namespace: crossplane-system
stringData:
    credentials: ENC[AES256_GCM,data:nzujyXNyNUZh/IioPuXnmfN/+RKrSAvZsLV/k2lxMDGNAw0i6QAcyYEYyBv6tOENT5S6by95Nm/7t/BX8RiCgVcDWK5N7kTIfViTPEi1HTvqNjvcqeok1lg11enYAF9fj0AT/nZ1eTpKLLZUIFdtCqecRjZghh7qaRpbrESEpgKYbIXKBJTgAzx2DLnqexy6Ggn6oWU7WLnTkNdPU/oFl6TKr6BocryObO9MEhbVqEcadiUuRgCy0Jx2io75ZmXPnTha3b1bB5P0ULTpZRZAXRkWImuegPRpClLpfdrlXd4f1T/xz2KMJ4mWxzm0F0PyWOSp9aDYwUjvLlceuSHJ3RQWGWQ3iWQJtmvUlhyPW21xZqJ65JslB989v85ll59DGyxpex37lB6DJujn9Rr8P+/TWLmGpXSuMr1zbYhqIKzZtA39xHC+z6qkVlIWJuF352YU8FGyMMjG3zCLnG8yjwTAAf8c91EIJVQRIobg2KbQ3IgXPEVD6Jwncf1UyfvfaqOzJt7qduvjlxC4c3FHX13mNa5eowyGsi6Fh9CpsNnPJ2AGNg4ikb5q3SovOI1s5hgEYTFW7szoneiqfGL1G1E48T/HD3i3AMjRqRLVs4/35o7UlU7pY9xIxqTCMzpbZv38Hms4qdLv4qzfnx6zAepOb49lZwx22n20MOETll75Ko2zxHClR6uC4+MvDcMcR+sfTiQLSasdrjODU19xH8gP57oDPlBOG16m0+kD0AhTQyH64Eisr9EXNP3oMdn9SBPd3vWwcK/exUxl3e4F6QFBPJIrbciHgGmtYs2pLNX0tCvug4g0J2XELurbRvWY+r3dqqJAi6orYlyfoOSdS4j9dbt1yo3WISTtpJxC2Vs03o/Xr++z6ciU1BA9WMNprWeEWL604NZ4wXe3E5Ai,iv:+T3mViBZtflRdAGyEcceYWSESc5+tZLkar0WYFhxscE=,tag:4K3519XUKBa7VudKwXnAYg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aDFKYjZmSURJbm1rQlU1
            alNQT0FFYmRKUFpyZVNucENhMUxWdmt6Y2kwClZzZ0FsZCsyajhmdUNnaWl4TWRv
            OElyVytRY0dhUzYrcE5tN0J5cXZDaE0KLS0tIGJlNjBDb01zZUpXL2FsT1lNYTk5
            UlJRV0Zicys2MEh6NUZEWWhqc0ZkQlUKwNcIMJ1dl/vm1fIRiE90Vj8X4MeU2szE
            5xS+dwwkj+n2To0Hxd4pmmbRkfVpMsnhAlxPyt9ErmrVj0qbmC9tWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:58:23Z"
    mac: ENC[AES256_GCM,data:fdNHnNrJVGdTFyr5fCqD/TZfOFbJX6so7Lg9nXz9yIECB6nbfTd9+/YT1TgRUFWnIRCeHKwzGjA62z7ordidKGBSf05jAa+XvLsTl/GdtfnchzHLU+2QsG51uCXApRTkVq3f3A531HArxfQH+JDK5kwJTsToYGiq/XKxiwWnlnQ=,iv:v33gV6YNLSs44WWJsr8vn9FsMcMsrPGS1h+uCGNSGJI=,tag:TNS7eoWEGvKHxIuJXY26SA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
