apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../../../base/apps/monitoring
    - authentik
    - kube-prometheus-stack
    - longhorn
    - loki
    - mktxp
    - openfga
    - uptime-kuma
