apiVersion: v1
kind: Secret
metadata:
    name: mktxp-credentials
    namespace: mktxp
stringData:
    credentials.yml: ENC[AES256_GCM,data:Sv6VZTZkSzKxAFoZRi6X+pXH+3AVMMTAE4HE7GHfqt4Mtiw5e8QGR02Pt1fy7lsmshajOPPFF7D92y4=,iv:kzHkfdd0ACHtfzWtg69wIYDNXJrjQizGdKDZaUzTvHE=,tag:5lBfvniHfLI3eudTJDmmpQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZ3ZKQTg0ZjU2bTloSStG
            R0w2YzB1Qjl3S3ZFc3BUbkp2QzZEa1hURm1JClNrbTNTZy9Idnp0K1dPS0Q5VzhW
            elhtY2RMYVVadU02dEpjVTlRbmtCOG8KLS0tIHU4SzBFYUZORUNJMlVQekV5N2Vk
            RVBqYWpFOERoT1pmR3NERFBNcjh2QVUKSIFyK/H06q+M8HRNv2jDAfMTtEiWj7DM
            DQZcAqCwC3w0G2zZVAtwhM3HD16tCCbmLypTH5TvNNhZ7253Alcopw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T20:38:28Z"
    mac: ENC[AES256_GCM,data:GqxT76MWM6edEV+8RcAo3yE8NdOLdoctO8tNXa8blcsF3dFQjQPgaB5Tj2jTNnWEBFITfFOI68jyTNfSrohuNyA6M6cNSY/iCy8oOQGTUFCJSfMvsKWqDq9rKGp5jX4ps+l3mSDX+IeJDYIHbVdmjW5CQRSgpUyxvv6NGWu+1ak=,iv:0nWd5VK2ujayqn6w2HUA+tg+NZYFFLOrHxfr/V7pAG8=,tag:DJA+0zyOIJIqK1TK5Ri6fg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
