name: Renovate

on:
    schedule:
        - cron: '0 6 * * *'
    workflow_dispatch: {}

jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  ref: main

            - name: Self-hosted Renovate
              uses: renovatebot/github-action@v46.3.4
              env:
                  RENOVATE_REPOSITORIES: '["phorge-fr/Hangar"]'
              with:
                  configurationFile: renovate.json
                  token: '${{ secrets.RENOVATE_TOKEN }}'
